# Adapted from base16-qutebrowser:
# https://github.com/theova/base16-qutebrowser/blob/main/.github/workflows/update.yml

name: Build the latest base16 colorschemes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install base16
        run: npm install base16-builder-node
      - name: Fetch the repository code
        uses: actions/checkout@v2
      - name: Run make
        run: make
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Build the latest base16 colorschemes
          branch: ${{ github.head_ref }}
