# Adapted from base16-qutebrowser:
# https://github.com/theova/base16-qutebrowser/blob/main/.github/workflows/update.yml

name: Build the latest base16 colorschemes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0}
      - name: Install base16
        run: npm install -g base16-builder-node
      - name: Fetch the repository code
        uses: actions/checkout@v2
      - name: Run make
        run: make
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Build the latest base16 colorschemes
          branch: ${{ github.head_ref }}
