name: Build the latest base16 colorschemes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week

env:
  REPO: 'base16/templates/base16-pyradio'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
      - name: Install base16
        run: npm install --location=global base16-builder-node
      - name: Set up templates dir
        run: mkdir -p base16/templates
      - name: Fetch the repository code
        uses: actions/checkout@v2
        with:
          path: $REPO
      - name: Run make
        run: cd $REPO && make
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Build the latest base16 colorschemes
          branch: ${{ github.head_ref }}
          repository: $REPO
